# Generated by Django 5.1.1 on 2024-09-13 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('age_likes', '0002_userage_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='userage',
            name='email',
            field=models.EmailField(default=0, max_length=254),
            preserve_default=False,
        ),
    ]
