# Generated by Django 5.1.1 on 2024-09-13 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('age_likes', '0003_userage_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='userage',
            name='phone',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
