# Generated by Django 5.1.1 on 2024-09-13 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('age_likes', '0004_userage_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='userage',
            name='f_name',
            field=models.CharField(default=0, max_length=60),
            preserve_default=False,
        ),
    ]
