# Generated by Django 5.1.1 on 2024-09-13 20:34

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('age_likes', '0006_userage_gender_alter_userage_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userage',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
