# Generated by Django 5.1.1 on 2024-09-13 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('age_likes', '0007_userage_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='userage',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
    ]
