# Generated by Django 5.1.1 on 2024-09-13 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('age_likes', '0008_userage_ip_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='userage',
            name='device_info',
            field=models.TextField(blank=True, null=True),
        ),
    ]
