# Generated by Django 5.1.1 on 2024-09-14 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('age_likes', '0011_userage_city_userage_country_userage_region_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userage',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
    ]
