# Generated by Django 5.1.1 on 2024-09-14 08:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('age_likes', '0012_userage_date_of_birth'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userage',
            name='age',
        ),
        migrations.RemoveField(
            model_name='userage',
            name='city',
        ),
        migrations.RemoveField(
            model_name='userage',
            name='country',
        ),
        migrations.RemoveField(
            model_name='userage',
            name='region',
        ),
    ]
